import { Course } from "../types/api.types";

export const mockCourses: Course[] = [
  {
    _id: "1",
    nameRU: "Йога",
    nameEN: "Yoga",
    description: "Йога для начинающих",
    directions: [],
    fitting: [],
    difficulty: "Начальный",
    durationInDays: 25,
    dailyDurationInMinutes: { from: 20, to: 50 },
    workouts: ["w1", "w2", "w3"],
  },
  {
    _id: "2",
    nameRU: "Стретчинг",
    nameEN: "Stretching",
    description: "Растяжка",
    directions: [],
    fitting: [],
    difficulty: "Средний",
    durationInDays: 25,
    dailyDurationInMinutes: { from: 20, to: 50 },
    workouts: ["w1", "w2", "w3"],
  },
  {
    _id: "3",
    nameRU: "Фитнес",
    nameEN: "Fitness",
    description: "Фитнес тренировки",
    directions: [],
    fitting: [],
    difficulty: "Продвинутый",
    durationInDays: 25,
    dailyDurationInMinutes: { from: 20, to: 50 },
    workouts: ["w1", "w2", "w3"],
  },
];
